In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\HR_Job_Placement_Dataset.csv")

In [3]:
df.shape

(51500, 26)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51500 entries, 0 to 51499
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age_years                  51500 non-null  int64
 1   gender                     51500 non-null  str
 2   ssc_percentage             48919 non-null  float64
 3   hsc_percentage             49435 non-null  float64
 4   degree_percentage          51500 non-null  float64
 5   degree_specialization      51500 non-null  str
 6   technical_score            51500 non-null  float64
 7   aptitude_score             51500 non-null  float64
 8   communication_score        51500 non-null  float64
 9   skills_match_percentage    51500 non-null  float64
 10  certifications_count       51500 non-null  int64
 11  internship_experience      51500 non-null  str
 12  years_of_experience        51500 non-null  int64
 13  career_switch_willingness  43034 non-null  str
 14  relevant_experience        43074 non-null  str
 15  previous_ctc_lpa           51500 non-null  float64
 16  expected_ctc_lpa           51500 non-null  float64
 17  company_tier               51500 non-null  str
 18  job_role_match             45369 non-null  str
 19  competition_level          51500 non-null  str
 20  bond_requirement           51500 non-null  str
 21  notice_period_days         49918 non-null  float64
 22  layoff_history             43033 non-null  str
 23  employment_gap_months      50403 non-null  float64
 24  relocation_willingness     43025 non-null  str
 25  status                     51500 non-null  str
dtypes: float64(11), int64(3), str(12)
memory usage: 14.3 MB

In [5]:
df.head()

,age_years,gender,ssc_percentage,hsc_percentage,degree_percentage,degree_specialization,technical_score,aptitude_score,communication_score,skills_match_percentage,...,expected_ctc_lpa,company_tier,job_role_match,competition_level,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status
0,27,Male,65.061656,83.842578,75.856526,Computer Science,58.221909,89.566305,64.474484,79.548913,...,5.805850,Tier 3,Not Matched,Medium,Not Required,15.0,No,18.0,Not Willing,Not Placed
1,24,Male,67.885626,64.973305,73.093588,Electronics,71.927978,54.591971,61.077306,73.316134,...,10.807739,Tier 1,Matched,High,Required,0.0,NaN,NaN,Not Willing,Not Placed
2,33,Female,73.892471,68.834121,90.196460,Information Technology,72.445041,58.587088,79.494739,75.466980,...,5.476839,Tier 3,Not Matched,Low,Not Required,0.0,No,3.0,Not Willing,Placed
3,31,Male,74.145568,76.255126,75.586731,Mechanical,78.855676,61.022065,53.740386,73.676449,...,9.980580,Tier 2,Matched,Low,Not Required,0.0,Yes,6.0,NaN,Not Placed
4,28,Male,60.475937,65.786336,80.801010,Information Technology,68.286776,65.713731,61.438314,88.994847,...,8.921233,Tier 2,Matched,Medium,Not Required,0.0,No,3.0,Willing,Not Placed

In [6]:
df.isnull()

,age_years,gender,ssc_percentage,hsc_percentage,degree_percentage,degree_specialization,technical_score,aptitude_score,communication_score,skills_match_percentage,...,expected_ctc_lpa,company_tier,job_role_match,competition_level,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
51496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
51498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51499,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False